name: CI

on:
  push:
    branches:
      - main

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install vite
      run: npm install vite --save-dev
    - name: Install dependencies
      run: npm install

  build:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the app
      run: npm run predeploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy the app
      run: npm run deploy
